#!/usr/bin/env bash

# This script configures an Ubuntu server with:
# 1. Localhost resolve to 127.0.0.2
# 2. Facebook.com resolve to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
